title: debug.log
description: test

url: http://debug-log.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Archives
   url: /articles

social:
   github: debug-log
   facebook: goingwelltime
   email: sea900318@gmail.com

google_analytics: "UA-58263416-1"
